# these variables determine what parameters to use to filter data
FILTER_PROJECTS = True
FILTER_MODELS = True
FILTER_EXPERIMENTS = True
FILTER_FREQUENCIES = True
FILTER_REALMS = True
FILTER_VARIABLES = True


# the list of models, experiments, etc. to filter
MODELS = [
                    "GISS-E2-H",
                    "GISS-E2-R",
                    "CNRM-CM5",
                    "CanAM4",
                    "CanCM4",
                    "CanESM2",                    
                    "MIROC4h",
                    "MIROC5",
                    "MRI-CGCM3",
                    "NorESM1-M",
                    "bcc-csm1-1",
                    "inmcm4",
                    "gfdl-hiram-c180",                    
                    "HadCM3",
                    "HadGEM2-ES",
                    "hadgem2-a",
                    "IPSL-CM5A-LR"
                    "ccsm4",
                    "HadCM3",
                    "mpi-esm-lr",
                    "NorESM1-M",
          ]
EXPERIMENTS = [
                    "amip",
                    "amip4K",
                    "amip4xCO2",
                    "amipFuture",
                    "decadal1960",
                    "decadal1965",
                    "decadal1970",
                    "decadal1975",
                    "decadal1980",
                    "decadal1985",
                    "decadal1990",
                    "decadal1995",
                    "decadal1998",
                    "decadal1999",
                    "decadal2000",
                    "decadal2001",
                    "decadal2002",
                    "decadal2003",
                    "decadal2004",
                    "decadal2005",
                    "decadal2006",
                    "decadal2007",
                    "decadal2008",
                    "decadal2009",
                    "decadal2010",
                    "esmControl",
                    "historical",
                    "historicalExt",
                    "historicalGHG",
                    "historicalMisc",
                    "historicalNat",
                    "midHolocene",
                    "sst2030",
                    "sstClim",
                    "1pctCO2",
                    "abrupt4xCO2",
                    "aqua4K",
                    "aqua4xCO2",
                    "aquaControl",
                    "esmFdbk1",
                    "esmFdbk2",
                    "esmFixClim1",
                    "esmFixClim2",
                    "esmHistorical",
                    "esmrcp85",
                    "piControl",
                    "rcp26",
                    "rcp45",
                    "rcp60",
                    "rcp85",
                    "sstClim4xCO2",
                    "sstClimAerosol",
                    "sstClimSulfate",
                ]               
FREQUENCIES = [
                    "mon",
                    "yr",
                    "monclim",
                    "day",
                    "fixed",
                    "3hr",
                ]
REALMS = [
                    "atmos",
                    "land",
                    "landice",
                    "ocean",
                    "seaIce",
                ]          
VARIABLES = [var.replace(' ', '_') for var in [
                    "air pressure at sea level",
                    "air temperature",
                    "atmosphere water vapor content",
                    "convective precipitation flux",
                    "convective snowfall flux",
                    "eastward wind",
                    "geopotential height",
                    "large scale snowfall flux",
                    "northward wind",
                    "precipitation flux",
                    "rainfall flux",
                    "relative humidity",
                    "runoff flux",
                    "sea surface temperature",
                    "sea water x velocity",
                    "sea water y velocity",
                    "specific humidity",
                    "surface albedo",
                    "surface snow amount",
                    "surface snow area fraction",
                    "surface temperature",
                    "time",
                    "toa incoming shortwave flux",
                    "toa outgoing longwave flux",
                    "water evaporation flux",
                    "net downward radiative flux at top of atmosphere model",
                    "surface downward latent heat flux",
                    "surface net download longwave flux",
                    "surface upward latent heat flux",
                    "surface upward sensible heat flux",
                    "toa outgoing shortwave flux",
                    "sea ice area fraction",
                    "sea ice thickness",
                ]]


facets = [
          ('project', ['cmip5']),
          ('model', MODELS),
          ('experiment', EXPERIMENTS),
          ('time_frequency', FREQUENCIES),
          ('realm', REALMS),
          ('cf_standard_name', VARIABLES),
          #('variable_long_name', VARIABLES),
          ]
